// SPDX-FileCopyrightText: 2021 iteratec GmbH
//
// SPDX-License-Identifier: Apache-2.0

const docsConfig = {
    temp: "githubRepo", // Name of temporary folder, will be deleted after build
    repository: "secureCodeBox/secureCodeBox", // The repository url without the github part of the link
    targetPath: "docs", // This needs to be 'docs' for the docusaurus build, but you may specify a 'docs/<subdirectory>'
    srcDirs: ["scanners", "hooks"], // Directory names, relative to the root directory of the github project, containing the subdirectories with documentation
    sizeLimit: 500000, // Limit of file size, most importantly used for large findings.
    findingsDir: "findings", // Directory for large findings which exceeded sizeLimit
    branch: "main",

    // Configures files which will be copied from docsConfig.repository.
    // This is an array of config maps. The map has the properties
    // src: required source directory in main repository (docsConfig.repository)
    // dst: required target directory in this repository relative to config.targetPath
    // exclude: (optional) array of files to exclude from src, default is exclude nothing
    //
    // Example:
    // filesFromRepository: [
    //       {src: "foo", dst: "some/foo", exclude: ["snafu.md", "susfu.md"]},
    //       {src: "bar", dst: "some/bar"},
    //     ]
    filesFromRepository: [
      {
        src: "docs/adr",
        dst: "architecture/adr",
        exclude: ["adr_0000.md", "adr_README.md"],
      },
    ],
  },
  // This is to configure what to show at the homepage tile-view.
  integrationsConfig = {
    targetFile: "src/integrations.js", // Name of the target file to (over-)write
    integrationDirs: ["hooks", "scanners"], // Names of the directories relative to the root level of the `/docs` folder
    defaultIcon: "img/integrationIcons/Default.svg", // Default Icon when no imageUrl provided or could not resolve imageUrl
  },
  sidebarConfig = {
    sidebarName: "sidebars.json",
    // Sidebar gets merged with the entries autogenerated from the docs config listed above.
    // Entries in "sidebarStart" will be placed **before** the auto generated items
    // Entries in "sidebarEnd" will be placed **after** the auto generated items
    sidebarStart: {
      "Getting Started": [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
      "How To's": [
        {
          type: "autogenerated",
          dirName: "how-tos",
        },
      ],
    },
    sidebarEnd: {
      Architecture: [
        {
          type: "autogenerated",
          dirName: "architecture",
        },
      ],
      "API Reference": [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
      Contributing: [
        {
          type: "autogenerated",
          dirName: "contributing",
        },
      ],
      Experimental: [
        {
          type: "autogenerated",
          dirName: "experimental",
        },
      ],
    },
  };

module.exports = {
  docsConfig,
  integrationsConfig,
  sidebarConfig,
};
